### ISSUE TITLE
Finish business plan

### ISSUE THREAD

**Issue by PavelTrutman** [brmson/Personal-Assistant#3]
Finish parts:
- [x] Project description, motivation, state-of-the-art review
- [x] Detailed specification
- [x] Project planning
- [x] Risk analysis and contingency plans
- [x] Preliminary results

**Comment by PavelTrutman** [comment]
@drapejak @JBurant @konrajak please check final version of the business plan. (https://github.com/PavelTrutman/Personal-Assistant/blob/master/doc/businessPlan/businessPlan.pdf)

**Comment by konrajak** [comment]
@PavelTrutman seems ok to me

**Comment by PavelTrutman** [comment]
Business plan handed in.
